version: "3.8"
services:
    client:
        stdin_open: true
        container_name: react_web
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: gs/web
        ports:
            - "3000:3000"
        volumes:
            - ./app/node_modules
            - ./:/app
